# Docker Compose configuration for development environment
# This file is used to set up the development environment with PostgreSQL, Redis, Django, Celery, and optional Nginx.
# It defines the services, volumes, and environment variables for the development environment.

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-smartfunds_dev}
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-dev_password}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER:-postgres} -d ${DATABASE_NAME:-smartfunds_dev}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data_dev:/data

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume_dev:/app/static
      - media_volume_dev:/app/media
      # Cache pip packages for faster rebuilds
      - pip_cache:/root/.cache/pip
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env.development
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=smartfunds.settings.development
    stdin_open: true
    tty: true

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "8080:80"
    volumes:
      - static_volume_dev:/app/static:ro
      - media_volume_dev:/app/media:ro
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    profiles:
      - nginx

  celery:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: celery -A smartfunds_backend worker --loglevel=debug --concurrency=1
    volumes:
      - .:/app
      - pip_cache:/root/.cache/pip
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env.development
    environment:
      - DEBUG=1

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: celery -A smartfunds_backend beat --loglevel=debug --pidfile=/tmp/celerybeat.pid
    volumes:
      - .:/app
      - pip_cache:/root/.cache/pip
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env.development
    environment:
      - DEBUG=1

  # Development tools
  # mailhog:
  #   image: mailhog/mailhog:latest
  #   ports:
  #     - "1025:1025"  # SMTP
  #     - "8025:8025"  # Web UI
  #   profiles:
  #     - dev-tools

  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"
    depends_on:
      - db
    profiles:
      - dev-tools

volumes:
  postgres_data_dev:
  redis_data_dev:
  static_volume_dev:
  media_volume_dev:
  pip_cache: